In [2]:
## Web scrap script

import requests

page = requests.get("https://h1bdata.info/index.php?em=&job=Data+Scientist&city=&year=2018")
page

In [3]:
page.status_code
# successful download

200

In [17]:
# parsing the page with beautifulSoup

from bs4 import BeautifulSoup

soup = BeautifulSoup(page.content, 'lxml')

In [24]:
import pandas as pd

table = soup.find_all('table')[0]
df = pd.read_html(str(table))[0]
employer = df['EMPLOYER'].tolist()
job_title = df['JOB TITLE'].tolist()
base_sal = df['BASE SALARY'].tolist()
location = df['LOCATION'].tolist()
sub_date = df['SUBMIT DATE'].tolist()
srt_date = df['START DATE'].tolist()
case_status = df['CASE STATUS'].tolist()

In [26]:
len(employer)

1890

In [36]:
sal_table = pd.DataFrame({'employer':employer,
                         'job_title':job_title,
                         'base_sal':base_sal,
                         'location':location,
                         'sub_date':sub_date,
                         'srt_date':srt_date,
                         'case_status':case_status})
sal_table.sort_values('base_sal', ascending = False, inplace = True)
sal_table

,employer,job_title,base_sal,location,sub_date,srt_date,case_status
51,LARSON LIVING LABS LLC,DATA SCIENTIST,312000,"CAMBRIDGE, MA",03/21/2018,03/28/2018,CERTIFIED
52,LARSON LIVING LABS LLC,DATA SCIENTIST,312000,"CAMBRIDGE, MA",05/14/2018,06/01/2018,CERTIFIED
1889,STITCH FIX INC,DATA SCIENTIST,234000,"SAN FRANCISCO, CA",09/04/2018,10/15/2018,CERTIFIED
1888,STITCH FIX INC,DATA SCIENTIST,234000,"SAN FRANCISCO, CA",09/04/2018,10/15/2018,WITHDRAWN
1887,STITCH FIX INC,DATA SCIENTIST,234000,"SAN FRANCISCO, CA",08/02/2018,10/15/2018,CERTIFIED
1886,KENSHO TECHNOLOGIES LLC,DATA SCIENTIST,215000,"CAMBRIDGE, MA",05/09/2018,06/11/2018,CERTIFIED
1885,FACEBOOK INC,DATA SCIENTIST,215000,"MENLO PARK, CA",09/13/2018,09/24/2018,CERTIFIED
1884,AIRBNB INC,DATA SCIENTIST,210000,"SAN FRANCISCO, CA",05/22/2018,07/09/2018,CERTIFIED
1883,JINGCHI CORP,DATA SCIENTIST,205000,"SUNNYVALE, CA",03/20/2018,09/16/2018,CERTIFIED
1882,FACEBOOK INC,DATA SCIENTIST,201925,"MENLO PARK, CA",06/14/2018,11/24/2018,CERTIFIED
1881,AIRBNB INC,DATA SCIENTIST,200000,"SAN FRANCISCO, CA",08/09/2018,09/17/2018,CERTIFIED
1880,DATAROBOT INC,DATA SCIENTIST,200000,"JERSEY CITY, NJ",08/30/2018,10/15/2018,CERTIFIED
1879,AIRBNB INC,DATA SCIENTIST,190000,"SAN FRANCISCO, CA",02/20/2018,03/12/2018,CERTIFIED
1878,CITADEL AMERICAS LLC,DATA SCIENTIST,190000,"CHICAGO, IL",03/12/2018,09/06/2018,CERTIFIED
1877,APPLE INC,DATA SCIENTIST,185000,"CUPERTINO, CA",04/02/2018,04/16/2018,CERTIFIED
1876,FACEBOOK INC,DATA SCIENTIST,185000,"MENLO PARK, CA",08/23/2018,09/03/2018,CERTIFIED
1875,FACEBOOK INC,DATA SCIENTIST,185000,"MENLO PARK, CA",08/22/2018,09/04/2018,CERTIFIED
48,DATAROBOT INC,DATA SCIENTIST,182700,"BOSTON, MA",06/08/2018,07/15/2018,CERTIFIED
49,HALOS INSURANCE INC,DATA SCIENTIST,182700,"WASHINGTON DC, DC",07/13/2018,07/23/2018,CERTIFIED
50,HALOS INSURANCE INC,DATA SCIENTIST,182700,"CARY, NC",07/20/2018,07/23/2018,CERTIFIED
1868,FACEBOOK INC,DATA SCIENTIST,180000,"MENLO PARK, CA",01/18/2018,02/05/2018,CERTIFIED
1867,FACEBOOK INC,DATA SCIENTIST,180000,"MENLO PARK, CA",01/12/2018,01/29/2018,CERTIFIED
1873,VF SERVICES LLC,DATA SCIENTIST,180000,"ALAMEDA, CA",04/06/2018,04/30/2018,CERTIFIED
1869,FACEBOOK INC,DATA SCIENTIST,180000,"SEATTLE, WA",01/31/2018,02/12/2018,CERTIFIED
1870,AIRBNB INC,DATA SCIENTIST,180000,"SAN FRANCISCO, CA",06/27/2018,07/30/2018,CERTIFIED
1871,FACEBOOK INC,DATA SCIENTIST,180000,"MENLO PARK, CA",05/22/2018,08/27/2018,CERTIFIED
1872,FACEBOOK INC,DATA SCIENTIST,180000,"MENLO PARK, CA",08/28/2018,09/03/2018,CERTIFIED
1874,FACEBOOK INC,DATA SCIENTIST,180000,"MENLO PARK, CA",07/13/2018,07/23/2018,CERTIFIED
1866,AIRBNB INC,DATA SCIENTIST,178541,"SAN FRANCISCO, CA",02/07/2018,08/01/2018,CERTIFIED
1865,AIRBNB INC,DATA SCIENTIST,175723,"SAN FRANCISCO, CA",02/07/2018,08/01/2018,CERTIFIED
...,...,...,...,...,...,...,...
81,WAYFAIR LLC,DATA SCIENTIST,58219,"BOSTON, MA",03/14/2018,08/29/2018,CERTIFIED
80,WAYFAIR LLC,DATA SCIENTIST,58219,"BOSTON, MA",03/15/2018,09/13/2018,CERTIFIED
79,FIRST TECHNOLOGIES LLC,DATA SCIENTIST,57928,"COMSTOCK PARK, MI",03/20/2018,09/18/2018,CERTIFIED
76,PYRAMID TECHNOLOGY SOLUTIONS INC,DATA SCIENTIST,57554,"INDIANAPOLIS, IN",03/21/2018,09/03/2018,CERTIFIED
78,PYRAMID TECHNOLOGY SOLUTIONS INC,DATA SCIENTIST,57554,"INDIANAPOLIS, IN",03/21/2018,09/03/2018,CERTIFIED
77,PYRAMID TECHNOLOGY SOLUTIONS INC,DATA SCIENTIST,57554,"INDIANAPOLIS, IN",03/21/2018,09/03/2018,CERTIFIED
75,WOLFRAM ALPHA LLC,DATA SCIENTIST,57000,"CHAMPAIGN, IL",01/24/2018,07/26/2018,CERTIFIED
74,CUMMINS INC,DATA SCIENTIST,56880,"COLUMBUS, IN",03/05/2018,08/31/2018,CERTIFIED
73,CUMMINS INC,DATA SCIENTIST,56880,"COLUMBUS, IN",03/28/2018,09/10/2018,CERTIFIED
72,FORD MOTOR CREDIT COMPANY,DATA SCIENTIST,56700,"DEARBORN, MI",03/07/2018,04/03/2018,CERTIFIED
71,FIRST TECHNOLOGIES LLC,DATA SCIENTIST,56597,"TROY, MI",03/20/2018,09/18/2018,CERTIFIED
70,FIRST TECHNOLOGIES LLC,DATA SCIENTIST,56597,"GROSSE POINTE FARMS, MI",03/20/2018,09/18/2018,CERTIFIED
69,BRAINDO LLC,DATA SCIENTIST,56493,"PHILADELPHIA, PA",03/19/2018,09/14/2018,CERTIFIED
68,VERISHIP INC,DATA SCIENTIST,55000,"KANSAS CITY, MO",03/14/2018,09/13/2018,CERTIFIED
67,PANTON INC,DATA SCIENTIST,55000,"HOUSTON, TX",03/20/2018,09/01/2018,CERTIFIED
66,PEOPLETICKER LLC,DATA SCIENTIST,55000,"DELRAY BEACH, FL",03/21/2018,09/20/2018,CERTIFIED
65,THE STRATEGIC GROUP PR LLC,DATA SCIENTIST,54600,"DORADO, PR",03/20/2018,09/16/2018,CERTIFIED
63,NODELOGIX INC,DATA SCIENTIST,54579,"ITASCA, IL",03/21/2018,09/20/2018,CERTIFIED
62,CCC INFORMATION SERVICES INC,DATA SCIENTIST,54579,"CHICAGO, IL",02/15/2018,08/17/2018,CERTIFIED
64,CCC INFORMATION SERVICES INC,DATA SCIENTIST,54579,"CHICAGO, IL",03/12/2018,09/11/2018,CERTIFIED
61,CIBER GLOBAL LLC,DATA SCIENTIST,53768,"MADISON, MI",03/13/2018,09/12/2018,CERTIFIED
0,SRIVEN SYSTEMS OF TX INC,DATA SCIENTIST,52000,"MADISON, WI",03/07/2018,09/02/2018,CERTIFIED
60,GROUPCONNECT LLC,DATA SCIENTIST,52000,"CHICAGO, IL",02/28/2018,03/01/2018,CERTIFIED
59,GROUPECONNECT LLC,DATA SCIENTIST,52000,"CHICAGO, IL",04/09/2018,04/23/2018,CERTIFIED
58,BIG FUEL COMMUNICATIONS LLC,DATA SCIENTIST,52000,"CHICAGO, IL",02/21/2018,02/26/2018,WITHDRAWN
57,UBER TECHNOLOGIES INC,DATA SCIENTIST,50440,"PITTSBURGH, PA",01/02/2018,06/01/2018,CERTIFIED
56,HUMANA INSURANCE COMPANY,DATA SCIENTIST,50170,"IRVING, TX",04/30/2018,05/10/2018,CERTIFIED
55,COPART INC,DATA SCIENTIST,49088,"DALLAS, TX",01/26/2018,07/04/2018,CERTIFIED
54,CCC INFORMATION SERVICES INC,DATA SCIENTIST,45614,"AUSTIN, TX",03/08/2018,09/06/2018,CERTIFIED
53,RAMSAI SOFTWARE SOLUTIONS INC,DATA SCIENTIST,44574,"BRADENTON, FL",03/28/2018,09/27/2018,CERTIFIED